### ISSUE TITLE
Lay out core requirements for matterhorn replacement

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon-iiif-player#31]
## Description

After our initial meeting we came up with a long list of what we'd like to see. We need to refine that list to a set of core requirements and identify an MVP

## Done looks like

- A document is generated describing core requirements and separately an MVP

https://northwestern.box.com/s/4smygsjak4c09o7qrep4xn1jxpqutfxr

**Comment by joncameron** [comment]
@joncameron Schedule a meeting for to work on this document.

**Comment by cjcolvar** [comment]
@davidschober @joncameron I think this ticket should move over to `avalonmediasystem/avalon`.  It is currently in `avalonmediasystem/avalon-iiif-player`.

**Comment by joncameron** [comment]
@cjcolvar Thanks Chris, I've moved it to avalon-bundle as samvera-labs/avalon-bundle#207
